# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedlearn_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x65\x64learn_grpc.proto\x12\x04main\"D\n\x15\x43lientRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\"J\n\x16\x43lientRegisterResponse\x12\x19\n\x11\x63onfirmation_code\x18\x01 \x01(\x05\x12\x15\n\rcurrent_round\x18\x02 \x01(\r\"B\n\x14TrainingStartRequest\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\r\x12\x0e\n\x06\x65pochs\x18\x03 \x01(\r\"=\n\x15TrainingStartResponse\x12\x0f\n\x07weights\x18\x01 \x03(\x0c\x12\x13\n\x0bnum_samples\x18\x02 \x01(\r\"4\n\x16ModelEvaluationRequest\x12\x1a\n\x12\x61ggregated_weights\x18\x01 \x03(\x0c\"+\n\x17ModelEvaluationResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\"\x06\n\x04void2T\n\x03\x61pi\x12M\n\x0e\x43lientRegister\x12\x1b.main.ClientRegisterRequest\x1a\x1c.main.ClientRegisterResponse\"\x00\x32\xa6\x01\n\x06\x63lient\x12J\n\rTrainingStart\x12\x1a.main.TrainingStartRequest\x1a\x1b.main.TrainingStartResponse\"\x00\x12P\n\x0fModelEvaluation\x12\x1c.main.ModelEvaluationRequest\x1a\x1d.main.ModelEvaluationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fedlearn_grpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTREGISTERREQUEST._serialized_start=29
  _CLIENTREGISTERREQUEST._serialized_end=97
  _CLIENTREGISTERRESPONSE._serialized_start=99
  _CLIENTREGISTERRESPONSE._serialized_end=173
  _TRAININGSTARTREQUEST._serialized_start=175
  _TRAININGSTARTREQUEST._serialized_end=241
  _TRAININGSTARTRESPONSE._serialized_start=243
  _TRAININGSTARTRESPONSE._serialized_end=304
  _MODELEVALUATIONREQUEST._serialized_start=306
  _MODELEVALUATIONREQUEST._serialized_end=358
  _MODELEVALUATIONRESPONSE._serialized_start=360
  _MODELEVALUATIONRESPONSE._serialized_end=403
  _VOID._serialized_start=405
  _VOID._serialized_end=411
  _API._serialized_start=413
  _API._serialized_end=497
  _CLIENT._serialized_start=500
  _CLIENT._serialized_end=666
# @@protoc_insertion_point(module_scope)
