# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcCalc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x04main\"\x1b\n\tIntResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\'\n\x08Operands\x12\x0c\n\x04left\x18\x01 \x01(\x05\x12\r\n\x05right\x18\x02 \x01(\x05\x32V\n\x04\x43\x61lc\x12&\n\x03\x61\x64\x64\x12\x0e.main.Operands\x1a\x0f.main.IntResult\x12&\n\x03sub\x12\x0e.main.Operands\x1a\x0f.main.IntResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTRESULT._serialized_start=24
  _INTRESULT._serialized_end=51
  _OPERANDS._serialized_start=53
  _OPERANDS._serialized_end=92
  _CALC._serialized_start=94
  _CALC._serialized_end=180
# @@protoc_insertion_point(module_scope)
