/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcCalc.h"
#include <stdio.h>

int *
add_100_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Received task: %d + %d\n", argp->left, argp->right);
	result = argp->left + argp->right;

	return &result;
}

int *
sub_100_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Received task: %d - %d\n", argp->left, argp->right);
	result = argp->left - argp->right;

	return &result;
}
